services:
  - type: web
    name: mega-file-upload
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 8080"
    envVars:
      - key: FTP_HOST
        value: "ftp.example.com"
      - key: FTP_USER
        value: "your_ftp_username"
      - key: FTP_PASS
        value: "your_ftp_password"
      - key: FTP_PATH
        value: "/path/to/upload"
