services:
  - type: web
    name: mega-to-ftp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: FTP_HOST
        value: "your_ftp_host"
      - key: FTP_USER
        value: "your_ftp_user"
      - key: FTP_PASS
        value: "your_ftp_password"
